# Generated by Django 5.1.6 on 2025-02-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='college',
        ),
    ]
