# Generated by Django 5.1.6 on 2025-02-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0002_remove_students_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='p_email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
