# Generated by Django 5.1.6 on 2025-02-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0003_students_p_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='branch',
            new_name='department',
        ),
    ]
