# Generated by Django 5.1.6 on 2025-02-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0004_rename_branch_students_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
    ]
