# Generated by Django 5.1.6 on 2025-03-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0005_students_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=50, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('c_date', models.DateField(auto_now_add=True, null=True)),
                ('last_date', models.DateField(null=True)),
                ('cgpa', models.CharField(max_length=50, null=True)),
                ('arrears', models.CharField(max_length=50, null=True)),
                ('passout_year', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
