# Generated by Django 5.1.6 on 2025-03-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0006_placements'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='passout_year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
