# Generated by Django 5.1.6 on 2025-03-22 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0007_students_passout_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('certificate', models.FileField(null=True, upload_to='')),
                ('internship', models.CharField(max_length=200, null=True)),
                ('projects', models.CharField(max_length=200, null=True)),
                ('achivements', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('placement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='placement_app.placements')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='placement_app.students')),
            ],
        ),
    ]
