# Generated by Django 5.1.6 on 2025-03-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0008_applyplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyplacement',
            name='soft_skills',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applyplacement',
            name='technical_skills',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
