# Generated by Django 5.1.6 on 2025-03-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0009_applyplacement_soft_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyplacement',
            name='offer_letter',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
