# Generated by Django 5.1.6 on 2025-03-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0010_applyplacement_offer_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placements',
            name='arrears',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placements',
            name='cgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='placements',
            name='passout_year',
            field=models.IntegerField(null=True),
        ),
    ]
